### ISSUE TITLE
hidapi not found

### ISSUE THREAD

**Issue by SSoutham** [Looking-Glass/JoyconLib#17]
I'm new to unity and would love a walkthrough of how to properly set up the demo scene.  I keep running into errors about the hidapi not being x64 architecture, which causes it to fail to load, which then causes a dll not found exception

**Comment by everyone-else-stole-the-good-usernames** [comment]
Did you ever manage to fix your issue?

**Comment by SSoutham** [comment]
I ended up re creating the demo scene myself and it just worked.  Honestly though it's been a long time since I worked on that project since it was a school assignment.
