### ISSUE TITLE
Getting a error with hidapi.dll at build

### ISSUE THREAD

**Issue by Drnagrom** [Looking-Glass/JoyconLib#25]

**Comment by simonsteele24** [comment]
I ran into the same issue. Just redownload the package from here: https://github.com/Looking-Glass/JoyconLib/releases/tag/0.5 and then go to Assets->Import Package -> Custom Package and then choose the .unityproject file that is included in the download above

**Comment by leifstroman** [comment]
I'm experiencing the same issue.
Is there a newer version of joycon lib than the one you linked @simonsteele24 ?
The version you linked only supports one joycon and is quite old (2017).
