### ISSUE TITLE
Gyro or accelerometer

### ISSUE THREAD

**Issue by r3a1d3a1** [Looking-Glass/JoyconLib#42]
The demo video showcases 3D rotation which is usually done using gyro data.
I was wondering if this lib actually outputs accelerometer data or has it been mistaken for gyro?

**Comment by EmilioLizama** [comment]
Hello, in the Joycon.cs files, you can get the gyro data from the joycon with the GetGyro() method, and the accelerometer data with the GetAccel().

**Comment by r3a1d3a1** [comment]
Perfect. Thank you!
